name: Build and Deploy to Octopus
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Install Octopus Tools
      run: |
        mkdir /opt/octo
        pushd /opt/octo
        wget -O /opt/octo/octopus.zip https://download.octopusdeploy.com/octopus-tools/6.12.0/OctopusTools.6.12.0.portable.zip
        unzip /opt/octo/octopus.zip
        chmod +x /opt/octo/Octo
        popd
    - name: Build
      run: dotnet publish ScheduledTask.csproj --output published --configuration Release
    - name: Setup .NET Core 2.x for deployment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.207'
    - name: Deploy
      run: bash .github/workflows/deploy.sh
      env:
        OCTOPUS_CLI_API_KEY: ${{secrets.OCTOPUS_CLI_API_KEY}}

