name: Pre-release

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        source-url: https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: .\build.ps1 ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh