name: Test

on:
  push:
    branches-ignore:
      - main
      - 'release/**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: .\build.ps1 ${{secrets.GITHUB_TOKEN}} --no-pack
      shell: pwsh
